version: '3.8'

services:

  django:
    container_name: django
    build:
      context: ./ChatGptApi
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ChatGptApi/DjangoApp:/usr/src/app/
      - ./ChatGptApi/Content.csv:/usr/src/app/data/content.csv 
    ports:
      - 8089:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=0198JDF14H2HYZ8JF412HZ
      - ALLOWED_HOSTS=localhost,127.0.0.1
